name: Module pipeline

on:
  push:
    branches: main
  pull_request:
    branches: main
    types: [opened]

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Lint
        uses: golangci/golangci-lint-action@v3
      - name: Tests
        run: |
          go install github.com/jstemmer/go-junit-report@latest
          go test -v -race -coverprofile=coverage.txt -coverpkg=./... ./... -covermode=atomic | go-junit-report -set-exit-code > testreport.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test report            # Name of the check run which will be created
          path: testreport.xml    # Path to test results
          reporter: java-junit        # Format of test results
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
            command: monitor
      - name: Upload Snyk SARIF
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
      